# Generated by Django 4.2.2 on 2023-10-22 10:12

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to=posts.models.image_directory_path),
        ),
    ]
